# Generated by Django 4.2.7 on 2023-11-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bairro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_do_bairro", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_do_cidade", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Nickname",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_da_pessoa", models.CharField(max_length=255)),
                ("sobrenome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Rua",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_da_rua", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=255, null=True)),
                ("ponto_de_referencia", models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZonaCidade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("zona_cidade", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ZonaEstado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("zona_estado", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_estado", models.CharField(max_length=255)),
                (
                    "parte_estado",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.zonaestado"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bairro", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.bairro")),
                ("cidade", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.cidade")),
                ("estado", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.estado")),
                ("rua", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.rua")),
            ],
        ),
        migrations.AddField(
            model_name="cidade",
            name="parte_cidade",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.zonacidade"),
        ),
    ]
