# Generated by Django 4.2.7 on 2023-11-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ordem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.TextField()),
                ("data", models.DateTimeField()),
                (
                    "ordem",
                    models.CharField(
                        choices=[
                            ("CELULAR", "Ordem_celular"),
                            ("DESKTOP", "Ordem_desktop"),
                            ("NOTEBOOK", "Ordem_notebook"),
                            ("CONSOLE", "Ordem_console"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="cidade",
            name="parte_cidade",
        ),
        migrations.RemoveField(
            model_name="endereco",
            name="bairro",
        ),
        migrations.RemoveField(
            model_name="endereco",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="endereco",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="endereco",
            name="rua",
        ),
        migrations.RemoveField(
            model_name="estado",
            name="parte_estado",
        ),
        migrations.DeleteModel(
            name="Nickname",
        ),
        migrations.DeleteModel(
            name="Bairro",
        ),
        migrations.DeleteModel(
            name="Cidade",
        ),
        migrations.DeleteModel(
            name="Endereco",
        ),
        migrations.DeleteModel(
            name="Estado",
        ),
        migrations.DeleteModel(
            name="Rua",
        ),
        migrations.DeleteModel(
            name="ZonaCidade",
        ),
        migrations.DeleteModel(
            name="ZonaEstado",
        ),
    ]
