# Generated by Django 4.2.7 on 2023-11-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_seumodelo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seumodelo",
            name="modelo_do_equipamento",
            field=models.CharField(blank=True, choices=[], max_length=255),
        ),
    ]
