# Generated by Django 4.2.7 on 2023-11-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_seumodelo_modelo_do_equipamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seumodelo",
            name="modelo_do_equipamento",
        ),
        migrations.RemoveField(
            model_name="seumodelo",
            name="tipo_de_equipamento",
        ),
        migrations.AddField(
            model_name="seumodelo",
            name="escolha_principal",
            field=models.CharField(
                choices=[("opcao_1", "Opção 1"), ("opcao_2", "Opção 2")], default="opcao_1", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="seumodelo",
            name="sub_escolha",
            field=models.CharField(
                choices=[("sub_opcao_1", "Sub Opção 1"), ("sub_opcao_2", "Sub Opção 2")],
                default="sub_opcao_1",
                max_length=20,
            ),
        ),
    ]
