# Generated by Django 4.2.7 on 2023-11-22 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_seumodelo_escolha_principal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seumodelo",
            old_name="sub_escolha",
            new_name="diagnostico",
        ),
    ]
