# Generated by Django 4.2.7 on 2023-11-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_sub_escolha_seumodelo_diagnostico"),
    ]

    operations = [
        migrations.CreateModel(
            name="Celular",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "modelo_e_marca",
                    models.CharField(
                        choices=[
                            ("Apple", "Iphone 6"),
                            ("Apple", "Iphone 6 Plus"),
                            ("Apple", "Iphone 6s"),
                            ("Apple", "Iphone 6s Plus"),
                            ("Apple", "Iphone 7"),
                            ("Apple", "Iphone 7 Plus"),
                            ("Apple", "Iphone 8"),
                            ("Apple", "Iphone 8 Plus"),
                            ("Apple", "Iphone X"),
                            ("Apple", "Iphone Xs"),
                            ("Apple", "Iphone Xr"),
                            ("Apple", "Iphone XS MAX"),
                            ("Apple", "Iphone 11"),
                            ("Apple", "Iphone 11 Pro"),
                            ("Apple", "Iphone 11 Pro Max"),
                            ("Apple", "Iphone 12 Mini"),
                            ("Apple", "Iphone 12"),
                            ("Apple", "Iphone 12 Pro"),
                            ("Apple", "Iphone 12 Pro Max"),
                            ("Apple", "Iphone 13 Mini"),
                            ("Apple", "Iphone 13"),
                            ("Apple", "Iphone 13 Pro"),
                            ("Apple", "Iphone 13 Pro Max"),
                            ("Apple", "Iphone 14 Mini"),
                            ("Apple", "Iphone 14"),
                            ("Apple", "Iphone 14 Pro"),
                            ("Apple", "Iphone 14 Pro Max"),
                            ("Apple", "Iphone 15"),
                            ("Apple", "Iphone 15 Plus"),
                            ("Apple", "Iphone 15 Pro"),
                            ("Apple", "Iphone 15 Pro Max"),
                            ("Samsung", "Linha A"),
                            ("Samsung", "Linha M"),
                            ("Samsung", "Linha J"),
                            ("Samsung", "Linha S"),
                            ("Samsung", "Linha Z-Fold"),
                            ("Samsung", "Linha Z-Flip"),
                            ("Samsung", "Linha Tab A"),
                            ("Samsung", "Linha Tab S"),
                            ("Motorola", "Linha G"),
                            ("Motorola", "Linha E"),
                            ("Motorola", "Linha Raze"),
                            ("Motorola", "Linha Z"),
                            ("Motorola", "Linha One"),
                            ("Xiaomi", "Linha Redmi"),
                            ("Xiaomi", "Linha Redmi Note"),
                            ("Xiaomi", "Linha Poco"),
                            ("Xiaomi", "Linha Mi"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
