# Generated by Django 4.2.7 on 2023-11-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_celular_modelo_e_marca"),
    ]

    operations = [
        migrations.CreateModel(
            name="Console",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "marca_e_modelo",
                    models.CharField(
                        choices=[
                            ("Xbox", "Xbox 360"),
                            ("Xbox", "Xbox One Fat"),
                            ("Xbox", "Xbox One S"),
                            ("Xbox", "Xbox One X"),
                            ("Play", "Playstation 1"),
                            ("Play", "Playstation 2"),
                            ("Play", "Playstation 3 Fat 4 usb"),
                            ("Play", "Playstation 3 Fat"),
                            ("Play", "Playstation 3 Slim"),
                            ("Play", "Playstation 3 Super Slim"),
                            ("Play", "Playstation 4 Fat"),
                            ("Play", "Playstation 4 Slim"),
                            ("Play", "Playstation 4 Pro"),
                            ("Play", "Playstation 5"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
