# Generated by Django 4.2.7 on 2023-11-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_seumodelo_tipo_do_equipameto"),
    ]

    operations = [
        migrations.AddField(
            model_name="seumodelo",
            name="complemento_detalhes",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
