# Generated by Django 4.2.7 on 2023-11-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_console_diagnostico"),
    ]

    operations = [
        migrations.AddField(
            model_name="celular",
            name="diagnostico",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.seumodelo"),
        ),
    ]
