# Generated by Django 4.2.7 on 2023-11-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_celular_diagnostico"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seumodelo",
            name="complemento_detalhes",
        ),
        migrations.AddField(
            model_name="celular",
            name="complemento_detalhes",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="celular",
            name="data_e_horario",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="console",
            name="complemento_detalhes",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="console",
            name="data_e_horario",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="Desktop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("complemento_detalhes", models.CharField(blank=True, max_length=255)),
                ("data_e_horario", models.DateTimeField(null=True)),
                (
                    "diagnostico",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.seumodelo"),
                ),
            ],
        ),
    ]
