# Generated by Django 4.2.7 on 2023-11-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_notebook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celular",
            name="modelo_e_marca",
            field=models.CharField(
                choices=[
                    ("Motorola", "Motorola G"),
                    ("Motorola", "Motorola E"),
                    ("Motorola", "Motorola Raze"),
                    ("Motorola", "Motorola Z"),
                    ("Motorola", "Motorola One"),
                    ("Apple", "Iphone 6"),
                    ("Apple", "Iphone 6 Plus"),
                    ("Apple", "Iphone 6s"),
                    ("Apple", "Iphone 6s Plus"),
                    ("Apple", "Iphone 7"),
                    ("Apple", "Iphone 7 Plus"),
                    ("Apple", "Iphone 8"),
                    ("Apple", "Iphone 8 Plus"),
                    ("Apple", "Iphone X"),
                    ("Apple", "Iphone Xs"),
                    ("Apple", "Iphone Xr"),
                    ("Apple", "Iphone XS MAX"),
                    ("Apple", "Iphone 11"),
                    ("Apple", "Iphone 11 Pro"),
                    ("Apple", "Iphone 11 Pro Max"),
                    ("Apple", "Iphone 12 Mini"),
                    ("Apple", "Iphone 12"),
                    ("Apple", "Iphone 12 Pro"),
                    ("Apple", "Iphone 12 Pro Max"),
                    ("Apple", "Iphone 13 Mini"),
                    ("Apple", "Iphone 13"),
                    ("Apple", "Iphone 13 Pro"),
                    ("Apple", "Iphone 13 Pro Max"),
                    ("Apple", "Iphone 14 Mini"),
                    ("Apple", "Iphone 14"),
                    ("Apple", "Iphone 14 Pro"),
                    ("Apple", "Iphone 14 Pro Max"),
                    ("Apple", "Iphone 15"),
                    ("Apple", "Iphone 15 Plus"),
                    ("Apple", "Iphone 15 Pro"),
                    ("Apple", "Iphone 15 Pro Max"),
                    ("Samsung A", "Samsung Galaxy A"),
                    ("Samsung M", "Samsung Galaxy M"),
                    ("Samsung J", "Samsung Galaxy J"),
                    ("Samsung S", "Samsung Galaxy S"),
                    ("Samsung Z-Fold", "Samsung Galaxy Z-Fold"),
                    ("Samsung Z-Flip", "Samsung Galaxy Z-Flip"),
                    ("Samsung Tab A", "Samsung Galaxy Tab A"),
                    ("Samsung Tab S", "Samsung Galaxy Tab S"),
                    ("Xiaomi", "Xiaomi Redmi"),
                    ("Xiaomi", "Xiaomi Redmi Note"),
                    ("Xiaomi", "Xiaomi Poco"),
                    ("Xiaomi", "Xiaomi Mi"),
                ],
                max_length=255,
            ),
        ),
    ]
