# Generated by Django 4.2.7 on 2023-11-22 19:04

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_celular_modelo_e_marca"),
    ]

    operations = [
        migrations.AddField(
            model_name="celular",
            name="codigo_unico",
            field=models.CharField(default=secrets.token_urlsafe, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name="console",
            name="codigo_unico",
            field=models.CharField(default=secrets.token_urlsafe, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name="desktop",
            name="codigo_unico",
            field=models.CharField(default=secrets.token_urlsafe, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="codigo_unico",
            field=models.CharField(default=secrets.token_urlsafe, max_length=32, unique=True),
        ),
    ]
