# Generated by Django 4.2.7 on 2023-11-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_celular_codigo_unico_console_codigo_unico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordem",
            name="ordem",
            field=models.CharField(
                choices=[
                    ("CELULAR", "Ordem celular"),
                    ("DESKTOP", "Ordem desktop"),
                    ("NOTEBOOK", "Ordem notebook"),
                    ("CONSOLE", "Ordem console"),
                ],
                max_length=255,
            ),
        ),
    ]
