# Generated by Django 4.2.7 on 2023-11-22 19:32

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_ordem_ordem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celular",
            name="codigo_unico",
            field=models.CharField(default=secrets.token_urlsafe, max_length=43, unique=True),
        ),
    ]
